# Generated by Django 5.2.1 on 2025-09-13 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAbonoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='abonos/')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('es_principal', models.BooleanField(default=False)),
                ('tipo_abono', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='imagenes', to='tablas.tipoabono')),
            ],
            options={
                'db_table': 'tipo_abono_imagenes',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
